### ISSUE TITLE
Does not work with electron

### ISSUE THREAD

**Issue by kefniark** [olliet88/pdf-img-convert.js#1]
## Description
Apparently the dependence to `canvas` caused issues with other flavor of JS like electron
Seems like only node binding are managed

```
Error: The module '\\reader\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 76. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Kef\Documents\Projects\book-reader-local-proto\reader\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
```

**Comment by kefniark** [comment]
I think I will just take some inspiration from your code and switch the canvas by a real canvas.
I just need to extract few images like the cover anyway 😃 

Btw, I would suggest to change that `Sync` method by a promise you can `await`
```js
pdfData = new Uint8Array(fs.readFileSync(pdfURL));
```
by
```js
import util from 'util'
const readFile= util.promisify(fs.readFile);

...

pdfData = new Uint8Array(await readFile(pdfURL));
```

**Comment by olliet88** [comment]
Thanks for pointing this out. I'd only tested it on pure node and chose node-canvas accordingly. I'll try to find a workaround for this but in the meantime feel free to fork the repo and make the necessary changes for your use case. (Please do submit a PR if you find a solution that works for node too 🙂)

> I think I will just take some inspiration from your code and switch the canvas by a real canvas.
> I just need to extract few images like the cover anyway 😃
> 
> Btw, I would suggest to change that `Sync` method by a promise you can `await`
> 
> ```js
> pdfData = new Uint8Array(fs.readFileSync(pdfURL));
> ```
> 
> by
> 
> ```js
> import util from 'util'
> const readFile= util.promisify(fs.readFile);
> 
> ...
> 
> pdfData = new Uint8Array(await readFile(pdfURL));
> ```

I'll make this changes you suggested here - thanks for pointing this out too.

**Comment by Yarin4** [comment]
Hi guys,
Same issue for me, I tried to rebuild it after the installation but it still won't work
But great reactivity @olliet88 thanks!

**Comment by olliet88** [comment]
@Yarin4 just to double check - did you rebuild it against electron using `electron-rebuild` or against node using `npm rebuild`?

**Comment by Yarin4** [comment]
> 
> 
> @Yarin4 just to double check - did you rebuild it against electron using `electron-rebuild` or against node using `npm rebuild`?
> 
> If you rebuilt against node could you try rebuilding against electron and reporting back? It'd be really useful thanks.

I used electron-rebuild but I actually think I am missing a package I'll have to check again

**Comment by ivysrono** [comment]
Same issue for me
Electron 11.1.1

**Comment by ZhangZheng-GIS** [comment]
when I used electron-rebuild, it fails and reports an error.
```
⠴ Building module: canvas, Completed: 0C:\Workspace\ELECTRON\getPDFtext\get-pdf-text\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: 无法打开包括文件: “cairo.h”: No suc
h file or directory [C:\Workspace\ELECTRON\getPDFtext\get-pdf-te
xt\node_modules\canvas\build\canvas.vcxproj]
⠏ Building module
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Workspace\ELECTRON\getPDFtext\get-pdf-text\node_modules\canvas'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
```

**Comment by Tenpi** [comment]
You should update to master branch of node-canvas (v3.0.0) v2 has a lot of build issues with electron rebuild. The update also requires updating pdfjs-dist to master branch as well.

https://github.com/Automattic/node-canvas
https://github.com/mozilla/pdfjs-dist

**Comment by LionSR** [comment]
for 2.0.0

.../dist/fa782d78b72b06e169fa60a7d72fbab8.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 120. This version of Node.js requires
NODE_MODULE_VERSION 123. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)..
